import { jsPDF } from "jspdf";
import { getAdverseEvents, getBatch, getSae, getSite, getStudy } from "@/lib/server/repo";
import { requireRole, errorResponse } from "@/lib/server/auth";
import { appendAuditDirect } from "@/lib/server/audit";

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = await requireRole("Pharmacovigilance", "PI", "Ethics", "Admin");
    const { id } = await params;
    const sae = await getSae(id);
    if (!sae) return Response.json({ error: "Not found" }, { status: 404 });
    const [aes, study, site, batch] = await Promise.all([
      getAdverseEvents(),
      getStudy(sae.studyId),
      getSite(sae.siteId),
      sae.batchId ? getBatch(sae.batchId) : Promise.resolve(undefined),
    ]);
    const ae = aes.find((a) => a.id === sae.aeId);

    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const L = 50;
    let y = 60;

    const line = (label: string, value: string, gap = 16) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.text(label.toUpperCase(), L, y);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      const wrapped = doc.splitTextToSize(value, 495);
      doc.text(wrapped, L, y + 12);
      y += 12 + wrapped.length * 12 + gap - 10;
    };

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("CIOMS-I — SUSPECT ADVERSE REACTION REPORT", L, y);
    y += 18;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by AryaSetu (demonstration) · Synthetic data · Not a regulatory submission", L, y);
    y += 20;

    line("Report ID", sae.id);
    line("Study", `${study?.id ?? sae.studyId} — ${study?.shortTitle ?? ""} (${study?.ctriNumber ?? ""})`);
    line("Site", `${site?.name ?? sae.siteId}${site ? `, ${site.city}` : ""}`);
    line("Participant (synthetic ID)", sae.participantId);
    line("Reaction (as reported)", sae.term);
    line("MedDRA PT (DEMO dictionary)", `${sae.meddraPt}${ae ? ` · ${ae.meddraCode}` : ""}`);
    line("Seriousness criteria", sae.seriousnessCriteria.join("; "));
    line("Severity / Expectedness", `${sae.severity} / ${sae.expectedness}`);
    line("Awareness (T0)", new Date(sae.awarenessAt).toLocaleString("en-IN"));
    line("Initial report due (NDCT 24h)", new Date(sae.initialDueAt).toLocaleString("en-IN"));
    line("Full report due (NDCT 14d)", new Date(sae.fullDueAt).toLocaleString("en-IN"));
    line("Causality (WHO-UMC / Naranjo)", `${sae.whoUmc} / ${sae.naranjo} of 13`);
    if (ae) {
      line("Dechallenge", ae.dechallenge);
      line("Concomitant products", ae.concomitant.length ? ae.concomitant.join(", ") : "None");
    }
    if (batch) line("Suspect product / batch", `${batch.product} · Lot ${batch.id} · Status: ${batch.status}`);
    line("Narrative", sae.narrative || "—");

    y += 10;
    doc.setFontSize(8);
    doc.text(`Exported by ${user.name} (${user.role}) · ${new Date().toLocaleString("en-IN")} · Export written to audit chain`, L, y);

    await appendAuditDirect({
      actor: user.name,
      role: user.role,
      action: "CIOMS-I exported",
      entity: "SAE",
      entityId: sae.id,
      reason: "PDF generated for reporting workflow",
    });

    const pdf = doc.output("arraybuffer");
    return new Response(pdf, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="CIOMS-I_${sae.id}.pdf"`,
      },
    });
  } catch (e) {
    return errorResponse(e);
  }
}
